import tseslint from 'typescript-eslint';
import stylisticJs from '@stylistic/eslint-plugin-js';
import stylisticTs from '@stylistic/eslint-plugin-ts';
import jsdoc from 'eslint-plugin-jsdoc';
import tsdoc from 'eslint-plugin-tsdoc';
import jest from 'eslint-plugin-jest';

export default [
    {
        plugins: {
            '@stylistic/js': stylisticJs,
            jsdoc,
        },
        rules: {
            // Possible Problems
            'array-callback-return': ['warn'],
            'constructor-super': ['warn'],
            'for-direction': ['warn'],
            'getter-return': ['warn'],
            'no-async-promise-executor': ['warn'],
            'no-class-assign': ['warn'],
            'no-compare-neg-zero': ['warn'],
            'no-cond-assign': ['warn'],
            'no-const-assign': ['warn'],
            'no-constant-binary-expression': ['warn'],
            'no-constant-condition': ['warn'],
            'no-constructor-return': ['warn'],
            'no-control-regex': ['warn'],
            'no-debugger': ['warn'],
            'no-dupe-args': ['warn'],
            'no-dupe-class-members': ['warn'],
            'no-dupe-else-if': ['warn'],
            'no-dupe-keys': ['warn'],
            'no-duplicate-case': ['warn'],
            'no-duplicate-imports': ['warn'],
            'no-empty-character-class': ['warn'],
            'no-empty-pattern': ['warn'],
            'no-ex-assign': ['warn'],
            'no-func-assign': ['warn'],
            'no-import-assign': ['warn'],
            'no-inner-declarations': ['warn'],
            'no-invalid-regexp': ['warn'],
            'no-irregular-whitespace': ['warn'],
            'no-loss-of-precision': ['warn'],
            'no-misleading-character-class': ['warn'],
            'no-new-native-nonconstructor': ['warn'],
            'no-obj-calls': ['warn'],
            'no-promise-executor-return': ['warn'],
            'no-prototype-builtins': ['warn'],
            'no-self-assign': ['warn'],
            'no-self-compare': ['warn'],
            'no-setter-return': ['warn'],
            'no-sparse-arrays': ['warn'],
            'no-template-curly-in-string': ['warn'],
            'no-this-before-super': ['warn'],
            'no-unexpected-multiline': ['warn'],
            'no-unmodified-loop-condition': ['warn'],
            'no-unreachable': ['warn'],
            'no-unreachable-loop': ['warn'],
            'no-unsafe-finally': ['warn'],
            'no-unsafe-negation': ['warn'],
            'no-unsafe-optional-chaining': ['warn'],
            'no-unused-private-class-members': ['warn'],
            'no-unused-vars': ['warn', { caughtErrors: 'none' }],
            'no-use-before-define': ['warn'],
            'no-useless-assignment': ['warn'],
            'no-useless-backreference': ['warn'],
            'require-atomic-updates': ['warn'],
            'use-isnan': ['warn'],
            'valid-typeof': ['warn'],
            // Suggestions
            'accessor-pairs': ['warn'],
            'block-scoped-var': ['warn'],
            'camelcase': ['warn'],
            'consistent-this': ['warn'],
            'curly': ['warn'],
            'default-case': ['warn'],
            'default-case-last': ['warn'],
            'default-param-last': ['warn'],
            'dot-notation': ['warn'],
            'eqeqeq': ['warn'],
            'func-name-matching': ['warn'],
            'func-names': ['warn'],
            'func-style': ['warn', 'declaration'],
            'grouped-accessor-pairs': ['warn'],
            'logical-assignment-operators': ['warn'],
            'new-cap': ['warn'],
            'no-alert': ['warn'],
            'no-array-constructor': ['warn'],
            'no-caller': ['warn'],
            'no-case-declarations': ['warn'],
            'no-continue': ['warn'],
            'no-else-return': ['warn'],
            'no-empty': ['warn'],
            'no-empty-function': ['warn', { allow: ['arrowFunctions'] }],
            'no-empty-static-block': ['warn'],
            'no-eval': ['warn'],
            'no-extend-native': ['warn'],
            'no-extra-bind': ['warn'],
            'no-extra-boolean-cast': ['warn'],
            'no-extra-label': ['warn'],
            'no-global-assign': ['warn'],
            'no-implicit-coercion': ['warn'],
            'no-implicit-globals': ['warn'],
            'no-implied-eval': ['warn'],
            'no-invalid-this': ['warn'],
            'no-iterator': ['warn'],
            'no-labels': ['warn'],
            'no-lone-blocks': ['warn'],
            'no-loop-func': ['warn'],
            'no-multi-assign': ['warn'],
            'no-multi-str': ['warn'],
            'no-negated-condition': ['warn'],
            'no-nested-ternary': ['warn'],
            'no-new': ['warn'],
            'no-new-func': ['warn'],
            'no-new-wrappers': ['warn'],
            'no-nonoctal-decimal-escape': ['warn'],
            'no-object-constructor': ['warn'],
            'no-octal': ['warn'],
            'no-octal-escape': ['warn'],
            'no-proto': ['warn'],
            'no-regex-spaces': ['warn'],
            'no-return-assign': ['warn'],
            'no-script-url': ['warn'],
            'no-sequences': ['warn'],
            'no-shadow': ['warn'],
            'no-shadow-restricted-names': ['warn'],
            'no-throw-literal': ['warn'],
            'no-undef-init': ['warn'],
            'no-unneeded-ternary': ['warn'],
            'no-unused-expressions': ['warn'],
            'no-unused-labels': ['warn'],
            'no-useless-call': ['warn'],
            'no-useless-catch': ['warn'],
            'no-useless-computed-key': ['warn'],
            'no-useless-concat': ['warn'],
            'no-useless-constructor': ['warn'],
            'no-useless-escape': ['warn'],
            'no-useless-rename': ['warn'],
            'no-useless-return': ['warn'],
            'no-var': ['warn'],
            'no-void': ['warn'],
            'no-warning-comments': ['warn'],
            'no-with': ['warn'],
            'object-shorthand': ['warn'],
            'one-var': ['warn', 'never'],
            'operator-assignment': ['warn'],
            'prefer-arrow-callback': ['warn'],
            'prefer-const': ['warn'],
            'prefer-exponentiation-operator': ['warn'],
            'prefer-numeric-literals': ['warn'],
            'prefer-object-has-own': ['warn'],
            'prefer-object-spread': ['warn'],
            'prefer-promise-reject-errors': ['warn'],
            'prefer-regex-literals': ['warn'],
            'prefer-rest-params': ['warn'],
            'prefer-spread': ['warn'],
            'prefer-template': ['warn'],
            'radix': ['warn', 'as-needed'],
            'require-await': ['warn'],
            'require-unicode-regexp': ['warn'],
            'require-yield': ['warn'],
            'strict': ['warn'],
            'symbol-description': ['warn'],
            'yoda': ['warn'],
            // Layout & Formatting
            'unicode-bom': ['warn'],

            '@stylistic/js/arrow-parens': ['warn'],
            '@stylistic/js/comma-dangle': ['warn', 'always-multiline'],
            '@stylistic/js/comma-style': ['warn'],
            '@stylistic/js/dot-location': ['warn', 'property'],
            '@stylistic/js/eol-last': ['warn'],
            '@stylistic/js/linebreak-style': ['warn'],
            '@stylistic/js/max-statements-per-line': ['warn'],
            '@stylistic/js/new-parens': ['warn'],
            '@stylistic/js/no-confusing-arrow': ['warn'],
            '@stylistic/js/no-extra-parens': ['warn'],
            '@stylistic/js/no-extra-semi': ['warn'],
            '@stylistic/js/no-floating-decimal': ['warn'],
            '@stylistic/js/no-multiple-empty-lines': ['warn', { max: 1, maxEOF: 0 }],
            '@stylistic/js/operator-linebreak': ['warn', 'before'],
            '@stylistic/js/padded-blocks': ['warn', 'never'],
            '@stylistic/js/quote-props': ['warn', 'consistent-as-needed'],
            '@stylistic/js/quotes': ['warn', 'single'],
            '@stylistic/js/semi': ['warn'],
            '@stylistic/js/semi-style': ['warn'],
            '@stylistic/js/spaced-comment': ['warn'],

            'jsdoc/check-access': ['warn'],
            'jsdoc/check-alignment': ['warn'],
            'jsdoc/check-indentation': ['warn'],
            'jsdoc/check-line-alignment': ['warn'],
            'jsdoc/check-param-names': ['warn'],
            'jsdoc/check-property-names': ['warn'],
            'jsdoc/check-tag-names': ['warn'],
            'jsdoc/check-types': ['warn'],
            'jsdoc/check-values': ['warn'],
            'jsdoc/empty-tags': ['warn'],
            'jsdoc/implements-on-classes': ['warn'],
            'jsdoc/informative-docs': ['warn'],
            'jsdoc/multiline-blocks': ['warn'],
            'jsdoc/no-bad-blocks': ['warn'],
            'jsdoc/no-blank-block-descriptions': ['warn'],
            'jsdoc/no-blank-blocks': ['warn'],
            'jsdoc/no-multi-asterisks': ['warn'],
            'jsdoc/require-asterisk-prefix': ['warn'],
            'jsdoc/require-description': ['warn'],
            'jsdoc/require-description-complete-sentence': ['warn'],
            'jsdoc/require-hyphen-before-param-description': ['warn', 'never'],
            'jsdoc/require-param': ['warn'],
            'jsdoc/require-param-description': ['warn'],
            'jsdoc/require-param-name': ['warn'],
            'jsdoc/require-param-type': ['warn'],
            'jsdoc/require-property': ['warn'],
            'jsdoc/require-property-description': ['warn'],
            'jsdoc/require-property-name': ['warn'],
            'jsdoc/require-property-type': ['warn'],
            'jsdoc/require-returns': ['warn'],
            'jsdoc/require-returns-check': ['warn'],
            'jsdoc/require-returns-description': ['warn'],
            'jsdoc/require-returns-type': ['warn'],
            'jsdoc/require-throws': ['warn'],
            'jsdoc/require-yields': ['warn'],
            'jsdoc/require-yields-check': ['warn'],
            'jsdoc/tag-lines': ['warn', 'any', { startLines: 1 }],
            'jsdoc/valid-types': ['warn'],
        },
    },
    {
        files: [
            '**/__tests__/*',
        ],
        plugins: {
            jest,
        },
        rules: {
            'jest/consistent-test-it': ['warn'],
            'jest/expect-expect': ['warn'],
            'jest/no-alias-methods': ['warn'],
            'jest/no-commented-out-tests': ['warn'],
            'jest/no-conditional-in-test': ['warn'],
            'jest/no-confusing-set-timeout': ['warn'],
            'jest/no-deprecated-functions': ['warn'],
            'jest/no-disabled-tests': ['warn'],
            'jest/no-done-callback': ['warn'],
            'jest/no-duplicate-hooks': ['warn'],
            'jest/no-export': ['warn'],
            'jest/no-focused-tests': ['warn'],
            'jest/no-identical-title': ['warn'],
            'jest/no-jasmine-globals': ['warn'],
            'jest/no-mocks-import': ['warn'],
            'jest/no-standalone-expect': ['warn'],
            'jest/no-test-prefixes': ['warn'],
            'jest/no-test-return-statement': ['warn'],
            'jest/padding-around-after-all-blocks': ['warn'],
            'jest/padding-around-after-each-blocks': ['warn'],
            'jest/padding-around-before-all-blocks': ['warn'],
            'jest/padding-around-before-each-blocks': ['warn'],
            'jest/padding-around-describe-blocks': ['warn'],
            'jest/padding-around-test-blocks': ['warn'],
            'jest/prefer-called-with': ['warn'],
            'jest/prefer-comparison-matcher': ['warn'],
            'jest/prefer-each': ['warn'],
            'jest/prefer-equality-matcher': ['warn'],
            'jest/prefer-expect-resolves': ['warn'],
            'jest/prefer-hooks-in-order': ['warn'],
            'jest/prefer-hooks-on-top': ['warn'],
            'jest/prefer-jest-mocked': ['warn'],
            'jest/prefer-lowercase-title': ['warn'],
            'jest/prefer-mock-promise-shorthand': ['warn'],
            'jest/prefer-spy-on': ['warn'],
            'jest/prefer-strict-equal': ['warn'],
            'jest/prefer-to-be': ['warn'],
            'jest/prefer-to-contain': ['warn'],
            'jest/prefer-to-have-length': ['warn'],
            'jest/prefer-todo': ['warn'],
            'jest/require-hook': ['warn'],
            'jest/require-to-throw-message': ['warn'],
            'jest/valid-describe-callback': ['warn'],
            'jest/valid-expect': ['warn'],
            'jest/valid-expect-in-promise': ['warn'],
            'jest/valid-title': ['warn'],
        },
    },
    {
        files: [
            '**/*.ts',
        ],
        plugins: {
            '@typescript-eslint': tseslint.plugin,
            '@stylistic/ts': stylisticTs,
            tsdoc,
        },
        languageOptions: {
            parser: tseslint.parser,
            parserOptions: {
                project: true,
            },
        },
        rules: {
            // Possible Problems
            'no-dupe-class-members': ['off'],
            'no-unused-vars': ['off'],
            'no-use-before-define': ['off'],
            // Suggestions
            'default-param-last': ['off'],
            'dot-notation': ['off'],
            'no-array-constructor': ['off'],
            'no-empty-function': ['off'],
            'no-implied-eval': ['off'],
            'no-invalid-this': ['off'],
            'no-loop-func': ['off'],
            'no-shadow': ['off'],
            'no-throw-literal': ['off'],
            'no-unused-expressions': ['off'],
            'no-useless-constructor': ['off'],
            'prefer-promise-reject-errors': ['off'],
            'require-await': ['off'],

            '@typescript-eslint/adjacent-overload-signatures': ['warn'],
            '@typescript-eslint/array-type': ['warn'],
            '@typescript-eslint/await-thenable': ['warn'],
            '@typescript-eslint/ban-ts-comment': ['warn'],
            '@typescript-eslint/ban-tslint-comment': ['warn'],
            '@typescript-eslint/class-literal-property-style': ['warn'],
            '@typescript-eslint/consistent-generic-constructors': ['warn'],
            '@typescript-eslint/consistent-indexed-object-style': ['warn'],
            '@typescript-eslint/consistent-type-assertions': ['warn'],
            '@typescript-eslint/consistent-type-definitions': ['warn'],
            '@typescript-eslint/consistent-type-exports': ['warn'],
            '@typescript-eslint/consistent-type-imports': ['warn'],
            '@typescript-eslint/default-param-last': ['warn'],
            '@typescript-eslint/dot-notation': ['warn'],
            '@typescript-eslint/explicit-function-return-type': ['warn'],
            '@typescript-eslint/explicit-member-accessibility': ['warn'],
            '@typescript-eslint/explicit-module-boundary-types': ['warn'],
            '@typescript-eslint/method-signature-style': ['warn', 'method'],
            '@typescript-eslint/naming-convention': ['warn'],
            '@typescript-eslint/no-array-constructor': ['warn'],
            '@typescript-eslint/no-array-delete': ['warn'],
            '@typescript-eslint/no-base-to-string': ['warn'],
            '@typescript-eslint/no-confusing-non-null-assertion': ['warn'],
            '@typescript-eslint/no-confusing-void-expression': ['warn'],
            '@typescript-eslint/no-deprecated': ['warn'],
            '@typescript-eslint/no-dupe-class-members': ['warn'],
            '@typescript-eslint/no-duplicate-enum-values': ['warn'],
            '@typescript-eslint/no-duplicate-type-constituents': ['warn'],
            '@typescript-eslint/no-dynamic-delete': ['warn'],
            '@typescript-eslint/no-empty-function': ['warn', { allow: ['arrowFunctions'] }],
            '@typescript-eslint/no-empty-object-type': ['warn'],
            '@typescript-eslint/no-explicit-any': ['warn'],
            '@typescript-eslint/no-extra-non-null-assertion': ['warn'],
            '@typescript-eslint/no-extraneous-class': ['warn'],
            '@typescript-eslint/no-floating-promises': ['warn'],
            '@typescript-eslint/no-for-in-array': ['warn'],
            '@typescript-eslint/no-implied-eval': ['warn'],
            '@typescript-eslint/no-import-type-side-effects': ['warn'],
            '@typescript-eslint/no-inferrable-types': ['warn'],
            '@typescript-eslint/no-invalid-this': ['warn'],
            '@typescript-eslint/no-invalid-void-type': ['warn'],
            '@typescript-eslint/no-loop-func': ['warn'],
            '@typescript-eslint/no-meaningless-void-operator': ['warn'],
            '@typescript-eslint/no-misused-new': ['warn'],
            '@typescript-eslint/no-misused-promises': ['warn'],
            '@typescript-eslint/no-mixed-enums': ['warn'],
            '@typescript-eslint/no-namespace': ['warn'],
            '@typescript-eslint/no-non-null-asserted-nullish-coalescing': ['warn'],
            '@typescript-eslint/no-non-null-asserted-optional-chain': ['warn'],
            '@typescript-eslint/no-non-null-assertion': ['warn'],
            '@typescript-eslint/no-redundant-type-constituents': ['warn'],
            '@typescript-eslint/no-require-imports': ['warn'],
            '@typescript-eslint/no-shadow': ['warn'],
            '@typescript-eslint/no-this-alias': ['warn'],
            '@typescript-eslint/no-unnecessary-boolean-literal-compare': ['warn'],
            '@typescript-eslint/no-unnecessary-condition': ['warn'],
            '@typescript-eslint/no-unnecessary-parameter-property-assignment': ['warn'],
            '@typescript-eslint/no-unnecessary-qualifier': ['warn'],
            '@typescript-eslint/no-unnecessary-template-expression': ['warn'],
            '@typescript-eslint/no-unnecessary-type-arguments': ['warn'],
            '@typescript-eslint/no-unnecessary-type-assertion': ['warn'],
            '@typescript-eslint/no-unnecessary-type-constraint': ['warn'],
            '@typescript-eslint/no-unnecessary-type-parameters': ['warn'],
            '@typescript-eslint/no-unsafe-argument': ['warn'],
            '@typescript-eslint/no-unsafe-assignment': ['warn'],
            '@typescript-eslint/no-unsafe-call': ['warn'],
            '@typescript-eslint/no-unsafe-declaration-merging': ['warn'],
            '@typescript-eslint/no-unsafe-enum-comparison': ['warn'],
            '@typescript-eslint/no-unsafe-function-type': ['warn'],
            '@typescript-eslint/no-unsafe-member-access': ['warn'],
            '@typescript-eslint/no-unsafe-return': ['warn'],
            '@typescript-eslint/no-unsafe-type-assertion': ['warn'],
            '@typescript-eslint/no-unsafe-unary-minus': ['warn'],
            '@typescript-eslint/no-unused-expressions': ['warn'],
            '@typescript-eslint/no-unused-vars': ['warn', { caughtErrors: 'none' }],
            '@typescript-eslint/no-use-before-define': ['warn'],
            '@typescript-eslint/no-useless-constructor': ['warn'],
            '@typescript-eslint/no-useless-empty-export': ['warn'],
            '@typescript-eslint/no-wrapper-object-types': ['warn'],
            '@typescript-eslint/non-nullable-type-assertion-style': ['warn'],
            '@typescript-eslint/only-throw-error': ['warn'],
            '@typescript-eslint/parameter-properties': ['warn'],
            '@typescript-eslint/prefer-as-const': ['warn'],
            '@typescript-eslint/prefer-find': ['warn'],
            '@typescript-eslint/prefer-for-of': ['warn'],
            '@typescript-eslint/prefer-function-type': ['warn'],
            '@typescript-eslint/prefer-includes': ['warn'],
            '@typescript-eslint/prefer-literal-enum-member': ['warn'],
            '@typescript-eslint/prefer-namespace-keyword': ['warn'],
            '@typescript-eslint/prefer-nullish-coalescing': ['warn'],
            '@typescript-eslint/prefer-optional-chain': ['warn'],
            '@typescript-eslint/prefer-promise-reject-errors': ['warn'],
            '@typescript-eslint/prefer-readonly': ['warn'],
            '@typescript-eslint/prefer-reduce-type-parameter': ['warn'],
            '@typescript-eslint/prefer-regexp-exec': ['warn'],
            '@typescript-eslint/prefer-return-this-type': ['warn'],
            '@typescript-eslint/prefer-string-starts-ends-with': ['warn'],
            '@typescript-eslint/promise-function-async': ['warn'],
            '@typescript-eslint/related-getter-setter-pairs': ['warn'],
            '@typescript-eslint/require-array-sort-compare': ['warn'],
            '@typescript-eslint/require-await': ['warn'],
            '@typescript-eslint/restrict-plus-operands': ['warn'],
            '@typescript-eslint/restrict-template-expressions': ['warn'],
            '@typescript-eslint/switch-exhaustiveness-check': ['warn'],
            '@typescript-eslint/triple-slash-reference': ['warn'],
            '@typescript-eslint/typedef': ['warn'],
            '@typescript-eslint/unbound-method': ['warn'],
            '@typescript-eslint/unified-signatures': ['warn'],
            '@typescript-eslint/use-unknown-in-catch-callback-variable': ['warn'],

            '@stylistic/ts/comma-dangle': ['warn', 'always-multiline'],
            '@stylistic/ts/member-delimiter-style': ['warn'],
            '@stylistic/ts/no-extra-parens': ['warn'],
            '@stylistic/ts/no-extra-semi': ['warn'],
            '@stylistic/ts/quote-props': ['warn', 'consistent-as-needed'],
            '@stylistic/ts/quotes': ['warn', 'single'],
            '@stylistic/ts/semi': ['warn'],

            'jsdoc/check-template-names': ['warn'],
            'jsdoc/no-types': ['warn'],
            'jsdoc/require-template': ['warn'],

            'tsdoc/syntax': ['warn'],
        },
    },
    {
        files: [
            '**/__tests__/*.ts',
        ],
        rules: {
            '@typescript-eslint/unbound-method': ['off'],

            'jest/no-untyped-mock-factory': ['warn'],
            'jest/unbound-method': ['warn'],
        },
    },
];
